<table class="table">
    <tr>
        <th>Lekarz</th>        
        <th>Data wizyty</th>       
        <th>Operacje</th>
    </tr>
    <?php foreach ($patients as $patient) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($patient['physician']) ;?></td>
        <td><?php echo $this->escapeHtml($patient['visit_date']) ;?></td>
        
        <td>
         <a href="<?php echo $this->url('patient',
             array('action'=>'cancel', 'id' => $patient['id']));?>">Odwołaj</a>
         
     </td>
    </tr>
    <?php endforeach; ?>
</table>

