<table class="table">
    <tr>
        <th>Imię</th>        
        <th>Nazwisko</th>       
        <th>Telefon</th>
        <th>Operacje</th>
    </tr>
    <?php foreach ($patients as $patient) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($patient->name) ;?></td>
        <td><?php echo $this->escapeHtml($patient->surname) ;?></td>
        <td><?php echo $this->escapeHtml($patient->tel) ;?></td>
        
        <td>
         <a href="<?php echo $this->url('registration',
             array('action'=>'add', 'id' => $patient->id));?>">Zapisz na wizytę</a>
         
     </td>
    </tr>
    <?php endforeach; ?>
</table>


