<table class="table">
    <tr>
        <th>Imię</th>        
        <th>Nazwisko</th>       
        <th>Telefon</th>
        <th>Operacje</th>
    </tr>
    <?php foreach ($patients as $patient) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($patient->name) ;?></td>
        <td><?php echo $this->escapeHtml($patient->surname) ;?></td>
        <td><?php echo $this->escapeHtml($patient->tel) ;?></td>
        
        <td>
         <a href="<?php echo $this->url('registration',
             array('action'=>'one', 'param' => $patient->id));?>">Zapisz na wizytę</a>
         <?php if($this->session && $this->session->role === 'register') :?>
           <a href="<?php echo $this->url('patient',
             array('action'=>'edit', 'id' => $patient->id));?>">Edytuj</a>       
         <?php endif;?>
     </td>
    </tr>
    <?php endforeach; ?>
</table>


