<h1>Tworzenie nowego uzytkownika</h1>
<?php

echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('surname'));
echo $this->formRow($form->get('birthday'));
echo $this->formRow($form->get('tel'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('pesel'));
echo $this->formRow($form->get('password'));
?>
<div class="btn btn-success center-block">Dodaj</div>
<?php echo $this->form()->closeTag($form); ?>

<script>
$(document).ready(function() {
    $('.btn').click(function(){
        
        $('form').submit();
    });
});
</script>
