 <?php
//var_dump($schedulers);
 $title = 'Lista harmonogramów';
 $this->headTitle($title);



 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <form action="<?php echo $this->url('schedulerShow')?>" method="POST">
 <table class="table">
 <tr>
     <th>Lekarz <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="physician_id"></span></th>
     <th>Początek grafiku <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="date_start"></th>
     <th>Koniec grafiku <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="date_end"></th>
     <th>Operacje </th>
 </tr>
 <tr>
     <td><?php
     
     echo $this->formRow($physicians->get('physicianScheduler')); 
     ?></td>
     <td></td>
     <td></td>
     <td></td>
 </tr>
 <?php foreach ($schedulers as $schedule) : ?>
 <tr>
     <?php /*
     echo '<pre>';
          var_dump($schedule);
          echo '</pre>';*/
     ?>
     <td><?php echo $this->escapeHtml($schedule['name']." ".$schedule['surname']);?></td>
     <td><?php echo $this->escapeHtml($schedule['date_start']);?></td>
     <td><?php echo $this->escapeHtml($schedule['date_end']);?></td>
     <td>
         <a href="<?php echo $this->url('schedulerShow',
             array('action'=>'edit', 'id' => $schedule['id']));?>">Edytuj</a>
         <a href="<?php echo $this->url('schedulerShow',
             array('action'=>'delete', 'id' => $schedule['id']));?>">Kasuj</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
 </form>
 <script type="text/javascript">
     $(document).ready(function() {
    $('.glyphicon').click(function(){   
       $('form').append('<input type="hidden" name="orderBy" value="'+$(this).attr('name')+'" />');
       $('form').append('<input type="hidden" name="physicianId" value="'+$('#sel1').val()+'" />');
       $('form').submit();
    });
    $('#sel1').change(function(){
            console.log($(this).val());
       $('form').append('<input type="hidden" name="physicianId" value="'+$(this).val()+'" />');
       $('form').submit();
    });
});
     
     
</script>