<div class="row">
    <div class="col-md-12 ">
<div class="input-group">
<?php
$form->setAttribute('action', $this->url('administrator',array('action'=>'add')))->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('surname'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('roleSelect'));
echo $this->form()->closeTag($form);



?>
    <div class="btn btn-success center-block">Zapisz</div>
</div>
</div>
    </div>

<script>
$(document).ready(function() {
    $('.btn').click(function(){
        
        $('form').submit();
    });
});
</script>
