<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Spec-Med Poradnia')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="<?php echo $this->url('schedulerShow') ?>">Lista harmonogramów</a></li>
                        <li><a href="<?php echo $this->url('schedulerAdd') ?>">Dodaj harmonogram</a></li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pacjenci <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="<?php echo $this->url('patient') ?>">Lista pacjentów</a></li>
      <li><a href="<?php echo $this->url('patient',array('action'=>'add'));?>">Dodaj pacjenta</a></li>
      <li><a href="<?php echo $this->url('physician',array('action'=>'add')) ?>">Zarządzaj pacjentami</a></li>   
    </ul>                            
</li>                          
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Lekarze <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="<?php echo $this->url('physician') ?>">Lista lekarzy</a></li>
      <li><a href="<?php echo $this->url('physician',array('action'=>'add')) ?>">Zarządzaj lekarzami</a></li>   
    </ul>                            
</li>                  
                        
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Rejestracja <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="<?php echo $this->url('registration') ?>">Rejestracja</a></li>
      <li><a href="<?php echo $this->url('registrationShow') ?>">Lista rejestracji</a></li>            
    </ul>                            
</li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pacjent <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="<?php echo $this->url('registration') ?>">Rejestracja wizity</a></li>
      <li><a href="<?php echo $this->url('registrationShow') ?>">Odwoływanie wizyty</a></li>            
      <li><a href="<?php echo $this->url('registrationShow') ?>">Moje wizyty</a></li>            
      <li><a href="<?php echo $this->url('registrationShow') ?>">Edycja danych</a></li>            
    </ul>                            
</li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Rejestratorka <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="<?php echo $this->url('registration') ?>">Rejestracja pacjenta</a></li>
      <li><a href="<?php echo $this->url('registrationShow') ?>">Lista rejestracji</a></li>            
      <li><a href="<?php echo $this->url('registrationShow') ?>">Odwoływanie wizyt</a></li>            
      <li><a href="<?php echo $this->url('registrationShow') ?>">Wydruk listy pacjentów</a></li>            
      <li><a href="<?php echo $this->url('patient') ?>">Przegląd listy pacjentów</a></li>            
    </ul>                            
</li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Zend Framework 2" class="center-block" style="padding-bottom: 25px"/>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Krzysztof Malara <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
