<?php echo $this->doctype(); 
$this->session = new \Zend\Session\Container('loginData');

?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Spec-Med Poradnia')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/master.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                    
                    <li class="<?php echo $this->list_active; ?>">
                        <a href="<?php echo $this->url('register') ?>">Strona startowa</a></li>
                    <li class="<?php echo $this->registrationList_active; ?>">
                        <a href="<?php echo $this->url('registration',array('action'=>'show')) ?>">Zaplanowane wizyty</a></li>
                    <li class="<?php echo $this->registration_active; ?>">
                        <a href="<?php echo $this->url('registration') ?>">Zapisz pacjenta</a></li>
                    <li class="<?php echo $this->patient_active; ?>">
                        <a href="<?php echo $this->url('patient') ?>">Lista pacjentów</a></li>

                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div class="row pull-right">
           <?php 
           $this->session = new \Zend\Session\Container('loginData');
           if (!$this->session->login) : ?>
            
             <?php else : ?>   
            <p>Witaj <?php echo $this->session->name?><a href="<?php echo $this->url('autoryzacja',array('action'=>'logout'))?>"> Wyloguj</a></p>
             <?php endif; ?>
            </div>
            
            <a href='<?php echo $this->url('home')?>'><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Zend Framework 2" class="center-block" style="padding-bottom: 25px"/></a>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Krzysztof Malara <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>

