<div class="row">
    <div class="page-header">
  <h1>Rejestracja </h1>
  
</div>
    <h3>Wybierz swojego lekarza</h3>
    <?php foreach($lekarze as $physician) : ?>
    <div class="col-md-3">
        
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $physician->name ." ".$physician->surname?></div>
            <div id="physician_id" style="display:none"></div>
            <div class="panel-body">
                <img src="<?php echo $this->basePath('img/user.png') ?>" alt="user" class="img-responsive">
                <h4>Specjalizacja</h4>
                <p>Pellentesque pharetra ex et risus rutrum faucibus. Sed magna leo, molestie ut laoreet eget, dictum at purus. Nulla a feugiat ex. </p>                
               
            </div>
          </div>
    </div>
    <?php endforeach; ?>
</div>
<form method="POST" action="/rejestracja/stepone">
    
</form>

    


<style type="text/css"> 
    .panel-body p {
        text-align: justify;
    }
    .panel:hover {
        background-color: yellow;
        cursor: pointer;
        
    }
    .panel-body h4 {
        font-weight: bolder;
    }
    
    
    
</style>

<script type="text/javascript">
    $('.btn').click(function(){
       console.log($(this).find('.panel-heading').css('background-color','red'));
       $(this).find('.panel-heading').css('background-color','red');
    });
    
    $('.panel').click(function(){
        $('form').append('<input type="hidden" name="physician_name" value="'+$(this).find('.panel-heading').html()+'">');
        $('form').submit();
    });
</script>

