 <form action="<?php echo $this->url('registrationShow')?>" method="POST">
<table class="table">
    <tr>
        <th>Pacjent <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="physician_id"></span></th>
        <th>Lekarz <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="physician_id"></span></th>
        <th>Data wizyty <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="physician_id"></span></th>
        <th>Data rejestracji <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="physician_id"></span></th>
        <th>Opcje</th>
    </tr>
    <tr>
        <td><?php echo $this->formRow($patient->get('patientSelect')); ?></td>
        <td><?php echo $this->formRow($physicians->get('physicianScheduler')); ?></td>
        
    </tr>
<?php foreach ($result as $val) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($val['patient']);?></td>
        <td><?php echo $this->escapeHtml($val['physician']);?></td>
        <td><?php echo $this->escapeHtml($val['visit_date']);?></td>
        <td><?php echo $this->escapeHtml($val['registration_date']);?></td>
        <td>
         <a href="<?php echo $this->url('registrationShow',
             array('action'=>'edit', 'id' => $val['id']));?>">Edytuj</a>
         <a href="<?php echo $this->url('registrationShow',
             array('action'=>'delete', 'id' => $val['id']));?>">Kasuj</a>
     </td>
    </tr>
    <?php endforeach; ?>
</table>
 
<script type="text/javascript">
$(document).ready(function() {

$('#patientSelect').change(function() {
       $('form').append('<input type="hidden" name="patientId" value="'+$(this).val()+'" />');
       $('form').submit();    
});
$('#sel1').change(function() {
       $('form').append('<input type="hidden" name="physicianId" value="'+$(this).val()+'" />');
       if ($.isNumeric($("#patientSelect").val()))
       {
           $('form').append('<input type="hidden" name="patientId" value="'+$("#patientSelect").val()+'" />');
       }
       $('form').submit();    
});
});
    
</script>