<table class="table">
 <tr>
     <th>Pacjent<span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="physician_id"></span></th>
     <th>Data wizyty<span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true" name="physician_id"></span></th>
     <th>Operacje <span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
     
     
 </tr>
 <?php foreach ($patients as $patient) : ?>
 <tr>
     
     <td><?php echo $this->escapeHtml($patient['patient']);?></td>
     <td><?php echo $this->escapeHtml($patient['visit_date']);?></td>
     <td>
         <a href="<?php echo $this->url('physician',
             array('action'=>'cancel', 'id' => $patient['id']));?>">Odwołaj</a>
         
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
