<div class="row">
    <div class="col-md-12">
        <h1>Oszczędzamy Twój czas!</h1>
    <h2>Skorzystaj z elektronicznej rejestracji!</h2>
    </div>
    
</div>
<div class="row">
    <div class="col-md-12">
        <img class="img-responsive" src="<?php echo $this->basePath('img/kolejka.jpg')?>" alt="banner" style="width: 100%">
    </div>
</div>
<style>
    h1 {
       color:#0E2BA5;
       font-weight: bolder;
       margin-bottom: 0.5em;
    }
    
    h2 {
        text-align: right;
        letter-spacing: 0.4em;
        color:#0E2BA5;
        margin-left: 2em;
        margin-bottom: 1.5em;
    }
    
    img {
        border-radius: 5px;
        -webkit-box-shadow: 16px 10px 19px 0px rgba(0,0,0,0.75);
-moz-box-shadow: 16px 10px 19px 0px rgba(0,0,0,0.75);
box-shadow: 16px 10px 19px 0px rgba(0,0,0,0.75);
    }
    
</style>